# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "tank/system/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    {
      device = "tank/local/nix";
      fsType = "zfs";

    };
  fileSystems."/etc" =
    {
      device = "tank/system/etc";
      fsType = "zfs";
    };


  fileSystems."/var" =
    {
      device = "tank/system/var";
      fsType = "zfs";
    };

  fileSystems."/home" =
    {
      device = "tank/user/home";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/5114-A782";
      fsType = "vfat";
    };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # high-resolution display
  # hardware.video.hidpi.enable = lib.mkDefault true;
}
